package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.data.models.ClientOrIssuerType
import com.a4a.g8invoicing.ui.shared.ScreenElement

// This object is created to manipulate client or issuer data,
// without using the Client.kt / Issuer.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class ClientOrIssuerState(
    var id: Int? = null,
    var type: ClientOrIssuerType? = null,
    var originalClientOrIssuerId: Int? = null, // ID du client original (pour les documents)
    var originalVersion: Int? = null, // Version du maître au moment de la copie (pour les documents)
    var version: Int? = null, // Version actuelle (pour les maîtres)
    var firstName: TextFieldValue? = null,
    var name: TextFieldValue = TextFieldValue(""),
    var addresses: List<AddressState>? = null,
    var phone: TextFieldValue? = null,
    var emails: List<EmailState>? = null, // Max 4 emails
    var notes: TextFieldValue? = null,
    // Default labels stay null so the form falls back to the localized stringResource
    // (FR: SIRET/TVA/RCS, DE: HRB/USt-IdNr./Steuer-Nr., EN: Reg. No./VAT/ID). Hardcoding
    // them here would pin every new client to French regardless of the active locale.
    // The user's own edits override this fallback once they type something.
    var companyId1Label: TextFieldValue? = null,
    var companyId1Number: TextFieldValue? = null,
    var companyId2Label: TextFieldValue? = null,
    var companyId2Number: TextFieldValue? = null,
    var companyId3Label: TextFieldValue? = null,
    var companyId3Number: TextFieldValue? = null,
    var logoPath: String? = null,
    // Franchise en base de TVA (micro-entrepreneur FR / Kleinunternehmer DE / etc.).
    // Significatif seulement quand type=ISSUER. Utilisé par le générateur Factur-X pour
    // forcer BT-118=E + mention légale correspondante au pays.
    var vatExempt: Boolean = false,
    // Vente intra-UE : émetteur dans un pays UE qui facture parfois à des clients dans
    // d'autres pays UE. Significatif seulement quand type=ISSUER + countryCode UE.
    // Débloque l'affichage du champ Product.type (SERVICE/GOODS) — inutile pour un
    // utilisateur non-UE ou qui ne facture que dans son propre pays.
    var intraEuSales: Boolean = false,
    var errors: MutableList<Pair<ScreenElement, String?>> = mutableListOf(),
)
