package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.data.models.ClientOrIssuerType
import com.a4a.g8invoicing.data.models.ClientType
import com.a4a.g8invoicing.ui.shared.ScreenElement

// This object is created to manipulate client or issuer data,
// without using the Client.kt / Issuer.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class ClientOrIssuerState(
    var id: Int? = null,
    var type: ClientOrIssuerType? = null,
    var originalClientOrIssuerId: Int? = null, // ID du client original (pour les documents)
    var originalVersion: Int? = null, // Version du maître au moment de la copie (pour les documents)
    var version: Int? = null, // Version actuelle (pour les maîtres)
    var firstName: TextFieldValue? = null,
    var name: TextFieldValue = TextFieldValue(""),
    var addresses: List<AddressState>? = null,
    var phone: TextFieldValue? = null,
    var emails: List<EmailState>? = null, // Max 4 emails
    var notes: TextFieldValue? = null,
    // Default labels stay null so the form falls back to the localized stringResource
    // (FR: SIRET/TVA/RCS, DE: HRB/USt-IdNr./Steuer-Nr., EN: Reg. No./VAT/ID). Hardcoding
    // them here would pin every new client to French regardless of the active locale.
    // The user's own edits override this fallback once they type something.
    var companyId1Label: TextFieldValue? = null,
    var companyId1Number: TextFieldValue? = null,
    var companyId2Label: TextFieldValue? = null,
    var companyId2Number: TextFieldValue? = null,
    var companyId3Label: TextFieldValue? = null,
    var companyId3Number: TextFieldValue? = null,
    var logoPath: String? = null,
    // Bank accounts attached to the issuer (empty for clients). Persisted in
    // the [IssuerBank] table — many-to-one. The payment-means picker on an
    // invoice lets the user pick one of these; the picked account's IBAN + BIC
    // freeze onto [DocumentClientOrIssuer.payment_iban/payment_bic] so an
    // already-emitted invoice keeps its bank details even if the master list
    // changes later.
    var banks: List<IssuerBankState> = emptyList(),
    // Frozen IBAN (BT-84) on this doc-side snapshot only (i.e. when this state
    // represents a DocumentClientOrIssuer, not a master issuer). Master issuers
    // carry their accounts under [banks] instead. Never populated on clients.
    var paymentIban: TextFieldValue? = null,
    // Frozen BIC (BT-86), same conditions as [paymentIban]. Optional — SEPA
    // "IBAN only" (2016) makes it redundant intra-SEPA; still useful for
    // international payments (UK post-Brexit, Switzerland, US…).
    var paymentBic: TextFieldValue? = null,
    // Frozen country (ISO 3166-1 alpha-2) of the picked bank. Drives the
    // rendered label on preview + PDF ("IBAN :" vs "N° de compte :").
    var paymentCountry: String? = null,
    // Franchise en base de TVA (micro-entrepreneur FR / Kleinunternehmer DE / etc.).
    // Significatif seulement quand type=ISSUER. Utilisé par le générateur Factur-X pour
    // forcer BT-118=E + mention légale correspondante au pays.
    var vatExempt: Boolean = false,
    // Vente intra-UE : émetteur dans un pays UE qui facture parfois à des clients dans
    // d'autres pays UE. Significatif seulement quand type=ISSUER + countryCode UE.
    // Débloque l'affichage du champ Product.type (SERVICE/GOODS) — inutile pour un
    // utilisateur non-UE ou qui ne facture que dans son propre pays.
    var intraEuSales: Boolean = false,
    // B2B (PROFESSIONAL) vs B2C (INDIVIDUAL). Only meaningful on clients — the
    // Factur-X export flow gates on this: professionals get electronic invoices,
    // individuals get plain PDF. Null = user hasn't answered → export surfaces
    // a modal to force the choice. Auto-filled to PROFESSIONAL on SIREN entry
    // (see ClientOrIssuerAddEditViewModel) but the user can override.
    var clientType: ClientType? = null,
    // Withholding tax (Spanish IRPF, Portuguese IRS retenção, etc.). Only shown
    // on the form when the issuer's country is in CountryCodes.RETENTION_COUNTRIES.
    // When true, new invoices/credit notes for this issuer auto-add a retention
    // line seeded from the previous doc's rate.
    var taxWithholdingEnabled: Boolean = false,
    var errors: MutableList<Pair<ScreenElement, String?>> = mutableListOf(),
)
