package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.data.models.ClientOrIssuerType
import com.a4a.g8invoicing.ui.shared.ScreenElement

// This object is created to manipulate client or issuer data,
// without using the Client.kt / Issuer.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class ClientOrIssuerState(
    var id: Int? = null,
    var type: ClientOrIssuerType? = null,
    var originalClientId: Int? = null, // ID du client original (pour les documents)
    var firstName: TextFieldValue? = null,
    var name: TextFieldValue = TextFieldValue(""),
    var addresses: List<AddressState>? = null,
    var phone: TextFieldValue? = null,
    var emails: List<EmailState>? = null, // Max 4 emails
    var notes: TextFieldValue? = null,
    var companyId1Label: TextFieldValue? = TextFieldValue("SIRET"),
    var companyId1Number: TextFieldValue? = null,
    var companyId2Label: TextFieldValue? = TextFieldValue("TVA"),
    var companyId2Number: TextFieldValue? = null,
    var companyId3Label: TextFieldValue? = TextFieldValue("RCS"),
    var companyId3Number: TextFieldValue? = null,
    var errors: MutableList<Pair<ScreenElement, String?>> = mutableListOf(),
)
