package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.ui.navigation.DocumentTag
import com.a4a.g8invoicing.ui.shared.DocumentType

// This Document is created to manipulate Document data,
// without using the DocumentSimple.kt generated by sql
// it allows to not specify the Document id (that will be auto-incremented)
// and to change properties values (var instead of val)

abstract class DocumentState {
    abstract var documentId: Int?
    abstract var documentType: DocumentType
    abstract var documentTag: DocumentTag
    abstract var documentNumber: TextFieldValue // TextFieldValue mandatory to control placing the cursor in the field
    abstract var documentDate: String
    abstract var reference: TextFieldValue?
    abstract var freeField: TextFieldValue?
    abstract var documentIssuer: ClientOrIssuerState?
    abstract var documentClient: ClientOrIssuerState?
    abstract var documentProducts: List<DocumentProductState>?
    abstract var documentTotalPrices: DocumentTotalPrices?
    abstract var currency: TextFieldValue
    abstract var footerText: TextFieldValue
    abstract var createdDate: String?
    // Frozen at document creation. null = no watermark (premium with watermark-removal
    // module active when the doc was created, OR pre-feature legacy doc). Not edited
    // afterwards — toggling the module later doesn't retroactively change existing docs.
    abstract var watermarkText: String?
    // Frozen at document creation. JSON map of the template labels resolved in the
    // current locale ({"invoice_number": "Facture N°", ...}). null = pre-feature legacy
    // doc — at render we fall back to `stringResource` (follows current locale).
    abstract var labelsSnapshot: String?
}
