package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.ui.navigation.DocumentTag
import com.a4a.g8invoicing.ui.shared.DocumentType

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)

data class InvoiceState(
    override var documentType: DocumentType = DocumentType.INVOICE,
    override var documentTag: DocumentTag = DocumentTag.DRAFT,
    override var documentId: Int? = null,
    override var documentNumber: TextFieldValue = TextFieldValue("F-001"),
    // Have to put a time "12:00:00" because of a bug, if we don't, DatePicker will show 1 day prior to current date
    // https://issuetracker.google.com/issues/281859606
    override var documentDate: String = "",
    override var reference: TextFieldValue? = null,
    override var freeField: TextFieldValue? = null,
    override var documentIssuer: ClientOrIssuerState? = null,
    override var documentClient: ClientOrIssuerState? = null,
    override var documentProducts: List<DocumentProductState>? = null,
    override var documentTotalPrices: DocumentTotalPrices? = null,
    override var currency: TextFieldValue = TextFieldValue(),
    var paymentStatus: Int = 0,
    var dueDate: String = "",
    override var footerText: TextFieldValue = TextFieldValue(),
    override var createdDate: String? = null,
    override var watermarkText: String? = null,
    override var labelsSnapshot: String? = null,
    override var showCurrencyAndAutoTaxColumn: Boolean = false,
    override var formatLocale: String? = null,
    // Single toggle that hides the "BL/D001 - <date>" and "Autres lignes" grouping
    // rows in the preview + PDF while keeping every product row visible. Rendered as
    // one eye icon per source-header block in the doc form, all wired to the same
    // boolean.
    var hideLinkedSourceHeaders: Boolean = false,
    // Payment-means chip selections — chip identities (enum names like
    // "TRANSFER", "PAYPAL"), NOT UN/CEFACT 4461 codes. PayPal + Stripe share
    // code 68; chip identity is what round-trips through the DB so both stay
    // distinguishable at reload. UN/CEFACT codes derive at Factur-X export
    // time via [unCefactCodesForExport] with the "empty → [1] Instrument not
    // defined" fallback. Empty/null = no info displayed on the PDF.
    // Default seeded on createNew() to {TRANSFER, CHEQUE, CASH} — the classic
    // FR B2B combo. Does NOT contain OTHER (see [paymentMeansOtherChecked]).
    var paymentMeansSelections: Set<String>? = null,
    // "Autre" chip state. Separate flag rather than a sentinel in selections
    // so the selections column stays 100% UN/CEFACT-clean. OTHER is UI-only:
    // never contributes a Token to segments, never renders on the invoice,
    // never exports to Factur-X — it's purely a marker for the user's picker.
    var paymentMeansOtherChecked: Boolean = false,
    // Structured payment-means label: a mixed list of Free text segments and
    // locked Token(code) segments (see PaymentLabelSegment). Chip toggles
    // append or remove tokens; the "Modifier le texte" modal edits the Free
    // portions around them, rejecting any edit that would delete a token.
    // Tokens render as their locale-appropriate mode label at flatten time,
    // so the persisted payload stays language-agnostic. Empty list = no block
    // rendered on preview + PDF.
    var paymentMeansSegments: List<com.a4a.g8invoicing.data.models.PaymentLabelSegment> = emptyList(),
    // Eye toggle inside the payment-means picker. true = the whole payment-means
    // block (label + list) is hidden on preview + PDF. Codes stay persisted so
    // Factur-X BT-81 data is preserved.
    var paymentMeansHidden: Boolean = false,
    // "Afficher les coordonnées bancaires" switch below the IBAN dropdown in
    // the payment-means picker. true = IBAN/BIC line skipped on preview + PDF.
    // Frozen fields on DocumentClientOrIssuer stay populated regardless.
    var paymentBankHidden: Boolean = false,
    // Structured bank-details label (same segments+tokens pattern as
    // paymentMeansSegments). Empty list = fall back to
    // defaultPaymentBankSegments() at render time.
    var paymentBankSegments: List<com.a4a.g8invoicing.data.models.PaymentBankSegment> = emptyList(),
    // BT-20 Payment Terms Description — free-text conditions, e.g. "Escompte pour
    // paiement anticipé : néant\nTaux de pénalités : néant\nPaiement sous 30 jours net".
    // Per-invoice (not on the issuer) since different clients can have different terms.
    // Default seeded on createNew() from getExistingPaymentTermsDescription() → last
    // used text → fallback to document_default_payment_terms (which carries the LME
    // legal mentions in FR).
    var paymentTermsDescription: TextFieldValue = TextFieldValue(),
) : DocumentState()
