package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class CompanyDataState(
    var id: Long? = null,
    var label: TextFieldValue? = null,
    var number: TextFieldValue? = null
)
