package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.R
import com.a4a.g8invoicing.Strings
import com.a4a.g8invoicing.data.ClientOrIssuerState


// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class DeliveryNoteState(
    override var documentType: String = Strings.get(R.string.delivery_note),
    override var documentId: Int = 0,
    override var documentNumber: TextFieldValue = TextFieldValue(Strings.get(R.string.document_default_number)),
    override var documentDate: String = Strings.get(R.string.document_default_date),
    override var orderNumber: TextFieldValue = TextFieldValue(),
    override var issuer: ClientOrIssuerState = ClientOrIssuerState(),
    override var client: ClientOrIssuerState = ClientOrIssuerState(),
    override var documentProducts: List<DocumentProductState> = listOf(),
    override var documentPrices: DocumentPrices = DocumentPrices(),
    override var currency: TextFieldValue = TextFieldValue(),
): Document()

