package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.R
import com.a4a.g8invoicing.Strings


// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class DeliveryNoteState(
    override var documentType: String = Strings.get(R.string.delivery_note),
    override var documentId: Int? = null,
    override var documentNumber: TextFieldValue = TextFieldValue(Strings.get(R.string.document_default_number)),
    override var documentDate: String = Strings.get(R.string.document_default_date),
    override var orderNumber: TextFieldValue = TextFieldValue(),
    override var documentIssuer: DocumentClientOrIssuerState? = null,
    override var documentClient: DocumentClientOrIssuerState? = null,
    override var documentProducts: List<DocumentProductState>? = null,
    override var documentPrices: DocumentPrices? = null,
    override var currency: TextFieldValue = TextFieldValue(),
): Document()

