package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.data.ClientOrIssuerState
import java.math.BigDecimal

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class DeliveryNoteState(
    var deliveryNoteId: Int? = null,
    var number: TextFieldValue? = null, // Mandatory to control placing the cursor in the field
    var deliveryDate: String? = null,
    var orderNumber: TextFieldValue? = null,
    var issuer: ClientOrIssuerState? = null,
    var client: ClientOrIssuerState? = null,
    var documentProducts: List<DocumentProductState>? = null,
    var documentPrices: DocumentPrices? = null,
    var currency: TextFieldValue? = null,
)

data class DocumentPrices(
    var totalPriceWithoutTax: BigDecimal? = null,
    var totalAmountsOfEachTax: MutableList<Pair<BigDecimal, BigDecimal>>? = null, //ex:  [(20.0, 7.2), (10.0, 2.4)]
    var totalPriceWithTax: BigDecimal? = null,
)