package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.ui.shared.DocumentType
import java.math.BigDecimal

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)

abstract class DocumentState {
    abstract var documentId: Int?
    abstract var documentType: DocumentType
    abstract var documentNumber: TextFieldValue // Mandatory to control placing the cursor in the field
    abstract var documentDate: String
    abstract var orderNumber: TextFieldValue?
    abstract var documentIssuer: DocumentClientOrIssuerState?
    abstract var documentClient: DocumentClientOrIssuerState?
    abstract var documentProducts: List<DocumentProductState>?
    abstract var documentPrices: DocumentPrices?
    abstract var currency: TextFieldValue
}

data class DocumentPrices(
    var totalPriceWithoutTax: BigDecimal? = null,
    var totalAmountsOfEachTax: MutableList<Pair<BigDecimal, BigDecimal>>? = null, //ex:  [(20.0, 7.2), (10.0, 2.4)]
    var totalPriceWithTax: BigDecimal? = null,
)
