package com.a4a.g8invoicing.ui.states

import androidx.compose.ui.text.input.TextFieldValue
import com.a4a.g8invoicing.R
import com.a4a.g8invoicing.Strings


// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class Invoice(
    override var documentType: String = Strings.get(R.string.invoice),
    override var documentId: Int,
    override var documentNumber: TextFieldValue,
    override var documentDate: String,
    override var orderNumber: TextFieldValue,
    override var issuer: ClientOrIssuerState,
    override var client: ClientOrIssuerState,
    override var documentProducts: List<DocumentProductState>,
    override var documentPrices: DocumentPrices,
    override var currency: TextFieldValue,
    var dueDate: String = Strings.get(R.string.invoice_due_date)
): Document()

