package com.a4a.g8invoicing.data

import androidx.compose.ui.text.input.TextFieldValue

// This object is created to manipulate client or issuer data,
// without using the Client.kt / Issuer.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class ClientOrIssuerEditable(
    var id: Int? = null,
    var firstName: TextFieldValue? = null,
    var name: TextFieldValue = TextFieldValue(""),
    var address1: TextFieldValue? = null,
    var address2: TextFieldValue? = null,
    var zipCode: TextFieldValue? = null,
    var city: TextFieldValue? = null,
    var phone: TextFieldValue? = null,
    var email: TextFieldValue? = null,
    var notes: TextFieldValue? = null,
    var companyData: List<CompanyDataEditable>? = null,
)
