package com.a4a.g8invoicing.data

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class CompanyDataEditable(
    var id: Long? = null,
    var label: String = "",
    var number: String = "",
)
