package com.a4a.g8invoicing.data

import androidx.compose.ui.text.input.TextFieldValue
import java.math.BigDecimal

// This Client is created to manipulate client data,
// without using the ClientSimple.kt generated by sql
// it allows to not specify the client id (that will be auto-incremented)
// and to change properties values (var instead of val)
data class DeliveryNoteEditable(
    var deliveryNoteId: Int? = null,
    var number: TextFieldValue? = null, // Mandatory to control placing the cursor in the field
    var deliveryDate: String? = null,
    var orderNumber: TextFieldValue? = null,
    var issuer: ClientOrIssuerEditable? = null,
    var client: ClientOrIssuerEditable? = null,
    var documentProducts: List<DocumentProductEditable>? = null,
    var totalPriceWithoutTax: BigDecimal? = null,
    var totalAmountsOfEachTax: MutableList<Pair<BigDecimal, BigDecimal>>? = null,
    var totalPriceWithTax: BigDecimal? = null,
    var currency: TextFieldValue? = null,
)
